
[env]
TERM = "alacritty"

[font]
size = 11.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"

[window]
opacity = 0.9

[window.padding]
x = 15
y = 15

[general]
import = ["/home/stego/workspace/myrepo/dotfiles/config/alacritty/dracula.toml"]
